//
//  ClaudeDocManager.swift
//  claude-maestro
//
//  Created by Jack Wakem on 14/1/2026.
//

import Foundation

class ClaudeDocManager {

    /// Detect run command based on common project configuration files
    static func detectRunCommand(for projectPath: String) -> String? {
        let fm = FileManager.default
        let baseURL = URL(fileURLWithPath: projectPath)

        // Check for package.json (Node.js)
        let packageJson = baseURL.appendingPathComponent("package.json")
        if fm.fileExists(atPath: packageJson.path),
           let data = try? Data(contentsOf: packageJson),
           let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
           let scripts = json["scripts"] as? [String: String] {
            if scripts["dev"] != nil { return "npm run dev" }
            if scripts["start"] != nil { return "npm start" }
        }

        // Check for Cargo.toml (Rust)
        if fm.fileExists(atPath: baseURL.appendingPathComponent("Cargo.toml").path) {
            return "cargo run"
        }

        // Check for Package.swift (Swift)
        if fm.fileExists(atPath: baseURL.appendingPathComponent("Package.swift").path) {
            return "swift run"
        }

        // Check for pyproject.toml (Python)
        if fm.fileExists(atPath: baseURL.appendingPathComponent("pyproject.toml").path) {
            return "python -m pytest"
        }

        // Check for requirements.txt (Python)
        if fm.fileExists(atPath: baseURL.appendingPathComponent("requirements.txt").path) {
            return "python main.py"
        }

        // Check for Makefile
        if fm.fileExists(atPath: baseURL.appendingPathComponent("Makefile").path) {
            return "make run"
        }

        // Check for go.mod (Go)
        if fm.fileExists(atPath: baseURL.appendingPathComponent("go.mod").path) {
            return "go run ."
        }

        return nil
    }

    /// Generate claude.md content for a project
    static func generateContent(
        projectPath: String,
        runCommand: String?,
        branch: String?,
        sessionId: Int,
        port: Int?
    ) -> String {
        var content = """
        # Claude Code Session Context

        This file provides context for Claude Code running in this worktree.

        ## Project Information
        - **Path:** \(projectPath)
        """

        if let branch = branch {
            content += "\n- **Branch:** \(branch)"
        }

        content += "\n- **Session ID:** \(sessionId)"

        if let port = port {
            content += "\n- **Assigned Port:** \(port)"
        }

        content += "\n\n## Running the Application\n"

        if let cmd = runCommand {
            content += """

            To run this application, use:
            ```bash
            \(cmd)
            ```
            """
        } else {
            content += """

            The run command has not been configured yet. Common commands:
            - `npm run dev` - Node.js projects
            - `swift run` - Swift packages
            - `cargo run` - Rust projects
            - `python main.py` - Python projects
            - `go run .` - Go projects
            """
        }

        content += """


        ## Session Notes

        This worktree is managed by Claude Maestro. Changes made here are isolated
        from other sessions working on different branches.

        ---
        *Auto-generated by Claude Maestro*
        """

        return content
    }

    /// Write claude.md to the specified directory
    static func writeClaudeMD(
        to directory: String,
        projectPath: String,
        runCommand: String?,
        branch: String?,
        sessionId: Int,
        port: Int?
    ) {
        let effectiveRunCommand = runCommand ?? detectRunCommand(for: directory)

        let content = generateContent(
            projectPath: projectPath,
            runCommand: effectiveRunCommand,
            branch: branch,
            sessionId: sessionId,
            port: port
        )

        let filePath = URL(fileURLWithPath: directory)
            .appendingPathComponent("claude.md")

        do {
            try content.write(to: filePath, atomically: true, encoding: .utf8)
        } catch {
            print("Failed to generate claude.md: \(error)")
        }
    }
}
